"""initial MediTrust schema"""
from alembic import op
import sqlalchemy as sa
revision="0001_initial"; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("users",sa.Column("id",sa.Integer,primary_key=True),sa.Column("full_name",sa.String(120),nullable=False),sa.Column("email",sa.String(255),unique=True),sa.Column("phone",sa.String(30),unique=True),sa.Column("hashed_password",sa.Text,nullable=False),sa.Column("role",sa.String(20),nullable=False),sa.Column("city",sa.String(120)),sa.Column("latitude",sa.Float),sa.Column("longitude",sa.Float),sa.Column("consent",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)))
    op.create_index("ix_users_email","users",["email"]); op.create_index("ix_users_phone","users",["phone"])
    op.create_table("hospitals",sa.Column("id",sa.String(80),primary_key=True),sa.Column("name",sa.String(200),nullable=False),sa.Column("tagline",sa.String(300)),sa.Column("type",sa.String(120)),sa.Column("address",sa.String(300),nullable=False),sa.Column("city",sa.String(120),nullable=False),sa.Column("phone",sa.String(40)),sa.Column("emergency_hotline",sa.String(40)),sa.Column("website",sa.String(300)),sa.Column("opening_hours",sa.String(300)),sa.Column("latitude",sa.Float,nullable=False),sa.Column("longitude",sa.Float,nullable=False),sa.Column("rating",sa.Float,server_default="0"),sa.Column("reviews_count",sa.Integer,server_default="0"),sa.Column("hospital_verified",sa.Boolean,server_default=sa.false()),sa.Column("quality_accreditation",sa.String(120)),sa.Column("is_24x7_emergency",sa.Boolean,server_default=sa.false()),sa.Column("has_pediatrics",sa.Boolean,server_default=sa.false()),sa.Column("has_diagnostics",sa.Boolean,server_default=sa.false()),sa.Column("er_wait_time",sa.String(80)),sa.Column("specialties",sa.JSON),sa.Column("facilities",sa.JSON),sa.Column("trust_breakdown",sa.JSON),sa.Column("overview",sa.Text),sa.Column("created_at",sa.DateTime(timezone=True)))
    for name,col in [("ix_hospitals_name","name"),("ix_hospitals_city","city"),("ix_hospitals_latitude","latitude"),("ix_hospitals_longitude","longitude"),("ix_hospitals_is_24x7_emergency","is_24x7_emergency")]: op.create_index(name,"hospitals",[col])
    op.create_table("doctors",sa.Column("id",sa.String(80),primary_key=True),sa.Column("name",sa.String(180),nullable=False),sa.Column("specialty",sa.String(160),nullable=False),sa.Column("experience",sa.String(80)),sa.Column("hospital_id",sa.String(80),sa.ForeignKey("hospitals.id")),sa.Column("hospital_label",sa.String(250)),sa.Column("rating",sa.Float,server_default="0"),sa.Column("reviews_count",sa.Integer,server_default="0"),sa.Column("available_today",sa.Boolean,server_default=sa.false()),sa.Column("avatar_bg",sa.String(30)),sa.Column("initials",sa.String(10)),sa.Column("consultation_fee",sa.String(40)),sa.Column("bio",sa.Text),sa.Column("verified",sa.Boolean,server_default=sa.false()),sa.Column("availability",sa.JSON))
    op.create_index("ix_doctors_name","doctors",["name"]); op.create_index("ix_doctors_specialty","doctors",["specialty"]); op.create_index("ix_doctors_hospital_id","doctors",["hospital_id"])
    op.create_table("appointments",sa.Column("id",sa.Integer,primary_key=True),sa.Column("patient_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("doctor_id",sa.String(80),sa.ForeignKey("doctors.id"),nullable=False),sa.Column("hospital_id",sa.String(80),sa.ForeignKey("hospitals.id")),sa.Column("appointment_date",sa.Date,nullable=False),sa.Column("appointment_time",sa.Time,nullable=False),sa.Column("appointment_type",sa.String(40),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("notes",sa.Text),sa.Column("created_at",sa.DateTime(timezone=True)))
    op.create_table("consultations",sa.Column("id",sa.Integer,primary_key=True),sa.Column("patient_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("doctor_id",sa.String(80),sa.ForeignKey("doctors.id"),nullable=False),sa.Column("appointment_id",sa.Integer,sa.ForeignKey("appointments.id")),sa.Column("scheduled_at",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("session_reference",sa.String(200)),sa.Column("notes",sa.Text))
    op.create_table("reviews",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("hospital_id",sa.String(80),sa.ForeignKey("hospitals.id",ondelete="CASCADE")),sa.Column("doctor_id",sa.String(80),sa.ForeignKey("doctors.id",ondelete="CASCADE")),sa.Column("rating",sa.Integer,nullable=False),sa.Column("comment",sa.Text,nullable=False),sa.Column("reviewer_name",sa.String(120)),sa.Column("created_at",sa.DateTime(timezone=True)))
    op.create_table("saved_hospitals",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("hospital_id",sa.String(80),sa.ForeignKey("hospitals.id",ondelete="CASCADE"),nullable=False),sa.UniqueConstraint("user_id","hospital_id",name="uq_saved_user_hospital"))
    op.create_table("notifications",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("title",sa.String(180),nullable=False),sa.Column("message",sa.Text,nullable=False),sa.Column("is_read",sa.Boolean,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True)))
    op.create_table("health_problems",sa.Column("id",sa.String(80),primary_key=True),sa.Column("name",sa.String(180),nullable=False),sa.Column("keywords",sa.JSON),sa.Column("recommended_departments",sa.JSON),sa.Column("relevant_hospital_ids",sa.JSON),sa.Column("guidance",sa.Text))
    op.create_table("stays",sa.Column("id",sa.String(100),primary_key=True),sa.Column("name",sa.String(180),nullable=False),sa.Column("type",sa.String(100),nullable=False),sa.Column("near_hospital_id",sa.String(80),sa.ForeignKey("hospitals.id"),nullable=False),sa.Column("address",sa.String(300),nullable=False),sa.Column("distance_from_hospital",sa.Float,nullable=False),sa.Column("verified",sa.Boolean,server_default=sa.false()),sa.Column("price_per_day",sa.Integer,nullable=False),sa.Column("food_per_day",sa.Integer,nullable=False),sa.Column("mandatory_charges",sa.Integer,nullable=False),sa.Column("long_stay_support",sa.Boolean,server_default=sa.false()),sa.Column("caregiver_friendly",sa.Boolean,server_default=sa.false()),sa.Column("accessible",sa.Boolean,server_default=sa.false()),sa.Column("facilities",sa.JSON),sa.Column("contact",sa.String(40)),sa.Column("overview",sa.Text),sa.Column("stay_breakdown",sa.JSON))

def downgrade():
    for t in ["stays","health_problems","notifications","saved_hospitals","reviews","consultations","appointments","doctors","hospitals","users"]: op.drop_table(t)
